spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/awssqsmessenger
    username: postgres
    password: nokia3410
  flyway:
    url: jdbc:postgresql://localhost:5432/awssqsmessenger
    user: postgres
    password: nokia3410
    locations: classpath:db/migration
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}

sqs:
  notifications:
    queue:
      name: ${SQS_QUEUE_NAME}
      region: ${SQS_QUEUE_REGION}